#!/usr/bin/env python3
"""Analyze Tracy CSV export and generate markdown report."""

import csv
import sys
from collections import defaultdict
from datetime import datetime
from pathlib import Path


def analyze_tracy_csv(csv_path):
    """Parse Tracy CSV and aggregate zone statistics."""
    zones = defaultdict(lambda: {
        'count': 0,
        'total_time': 0.0,
        'min': float('inf'),
        'max': 0.0,
        'times': []
    })

    with open(csv_path, 'r') as f:
        reader = csv.DictReader(f)
        for row in reader:
            name = row.get('name', row.get('zone', 'unknown'))

            # Tracy CSV has time in nanoseconds
            time_ns = int(row.get('exec_time', row.get('time', 0)))
            time_ms = time_ns / 1_000_000.0

            zones[name]['count'] += 1
            zones[name]['total_time'] += time_ms
            zones[name]['min'] = min(zones[name]['min'], time_ms)
            zones[name]['max'] = max(zones[name]['max'], time_ms)
            zones[name]['times'].append(time_ms)

    return zones


def percentile(values, p):
    """Calculate percentile of a sorted list."""
    if not values:
        return 0.0
    k = (len(values) - 1) * (p / 100.0)
    f = int(k)
    c = int(k) + 1
    if c >= len(values):
        return values[-1]
    d0 = values[f] * (c - k)
    d1 = values[c] * (k - f)
    return d0 + d1


def generate_markdown_report(zones, csv_path):
    """Generate markdown report from zone statistics."""
    sorted_zones = sorted(zones.items(), key=lambda x: x[1]['total_time'], reverse=True)

    # Calculate total profiled time
    total_time = sum(z['total_time'] for z in zones.values())

    print("# Tracy Profile Report\n")
    print(f"**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"**Source**: `{Path(csv_path).name}`\n")

    # Summary statistics
    print("## Summary\n")
    print(f"- **Total profiled time**: {total_time:.2f}ms")
    print(f"- **Unique zones**: {len(zones)}")
    print(f"- **Total samples**: {sum(z['count'] for z in zones.values())}\n")

    # Top 20 hotspots by total time
    print("## Top 20 Hotspots (by total time)\n")
    print("| Rank | Zone | Total (ms) | Calls | Avg (ms) | Min (ms) | Max (ms) | p50 (ms) | p95 (ms) | % Total |")
    print("|------|------|------------|-------|----------|----------|----------|----------|----------|---------|")

    for rank, (name, data) in enumerate(sorted_zones[:20], 1):
        avg = data['total_time'] / data['count']
        pct = (data['total_time'] / total_time * 100) if total_time > 0 else 0

        # Calculate percentiles
        times_sorted = sorted(data['times'])
        p50 = percentile(times_sorted, 50)
        p95 = percentile(times_sorted, 95)

        print(f"| {rank} | `{name}` | {data['total_time']:.2f} | {data['count']} | {avg:.2f} | {data['min']:.2f} | {data['max']:.2f} | {p50:.2f} | {p95:.2f} | {pct:.1f}% |")

    # Frame analysis (if present)
    frame_zones = {k: v for k, v in zones.items() if 'frame' in k.lower()}
    if frame_zones:
        print("\n## Frame Statistics\n")
        for name, data in frame_zones.items():
            avg_frame = data['total_time'] / data['count']
            fps = 1000.0 / avg_frame if avg_frame > 0 else 0
            print(f"### `{name}`\n")
            print(f"- **Average frame time**: {avg_frame:.2f}ms ({fps:.1f} FPS)")
            print(f"- **Frame count**: {data['count']}")
            print(f"- **Best frame**: {data['min']:.2f}ms")
            print(f"- **Worst frame**: {data['max']:.2f}ms")

            times_sorted = sorted(data['times'])
            p50 = percentile(times_sorted, 50)
            p95 = percentile(times_sorted, 95)
            p99 = percentile(times_sorted, 99)
            print(f"- **p50 frame time**: {p50:.2f}ms")
            print(f"- **p95 frame time**: {p95:.2f}ms ({1000.0/p95:.1f} FPS)")
            print(f"- **p99 frame time**: {p99:.2f}ms ({1000.0/p99:.1f} FPS)\n")

    # Slowest individual calls
    print("## Slowest Individual Calls\n")
    print("| Zone | Time (ms) |")
    print("|------|-----------|")

    all_slow_calls = []
    for name, data in zones.items():
        for t in data['times']:
            all_slow_calls.append((name, t))

    all_slow_calls.sort(key=lambda x: x[1], reverse=True)
    for name, time_ms in all_slow_calls[:10]:
        print(f"| `{name}` | {time_ms:.2f} |")

    print("\n---\n")
    print("*Generated by `scripts/analyze_tracy.py`*")


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 analyze_tracy.py <profile.csv>", file=sys.stderr)
        sys.exit(1)

    csv_path = sys.argv[1]

    if not Path(csv_path).exists():
        print(f"Error: File not found: {csv_path}", file=sys.stderr)
        sys.exit(1)

    zones = analyze_tracy_csv(csv_path)
    generate_markdown_report(zones, csv_path)


if __name__ == '__main__':
    main()
